name: 'Send notification on GitHub Action job status'
description: 'This action sends a custom notification on GitHub Action job status'
inputs:
  slack_bot_token:
    description: 'Slack Bot token'
    required: true
  slack_channel:
    description: 'Slack channel ID'
    required: true
  status:
    description: 'Job status'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send to Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel-id": "${{ inputs.slack_channel }}",
            "text": "${{ github.repository }} - ${{ github.workflow}} #${{ github.run_number }} - ${{ inputs.status }}\n`${{ github.job }}` job triggered by ${{ github.event_name }} in `${{ github.ref_name }}` branch/tag",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":github: - *${{ github.repository }}* - *${{ github.workflow}}* #${{ github.run_number }} - *${{ inputs.status }}*\n`${{ github.job }}` job triggered by ${{ github.event_name }} in `${{ github.ref_name }}` branch/tag"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
